### ISSUE TITLE
Please use built-in Ghost page images where available

### ISSUE THREAD

**Issue by rhester72** [xdumaine/ghost-aside#2]
The following changes will present the post image in the sidebar if available, otherwise the cover image if available (essentially moving the default header into index and adding a second double-conditional header into post):

```
$ diff ghost-aside-master/default.hbs ghost-aside/default.hbs
35,46d34
<       <header id="site-head" {{#if @blog.cover}}style="background-image: url({{@blog.cover}})"{{/if}}>
<               <div class="vertical">
<                       <div id="site-head-content" class="inner">
<
<                               {{#if @blog.logo}}<a id="blog-logo" href="{{@blog.url}}"><img src="{{@blog.logo}}" alt="Blog Logo" /></a>{{/if}}
<                               <h1 class="blog-title">{{@blog.title}}</h1>
<                               <h2 class="blog-description">{{@blog.description}}</h2>
<                               {{navigation}}
<                       </div>
<               </div>
<       </header>
<
```

```
$ diff ghost-aside-master/index.hbs ghost-aside/index.hbs
6a7,17
> <header id="site-head" {{#if @blog.cover}}style="background-image: url({{@blog.cover}})"{{/if}}>
>     <div class="vertical">
>         <div id="site-head-content" class="inner">
>
>             {{#if @blog.logo}}<a id="blog-logo" href="{{@blog.url}}"><img src="{{@blog.logo}}" alt="Blog Logo" /></a>{{/if}}
>             <h1 class="blog-title">{{@blog.title}}</h1>
>             <h2 class="blog-description">{{@blog.description}}</h2>
>             {{navigation}}
>         </div>
>     </div>
> </header>
```

```
]$ diff ghost-aside-master/post.hbs ghost-aside/post.hbs
5a6,20
> {{! Everything inside the #post tags pulls data from the post }}
> {{#post}}
>
> <header id="site-head" {{#if image}}style="background-image: url({{image}})"{{else}}{{#if @blog.cover}}style="background-image: url({{@blog.cover}})"{{/if}}{{/if}}>
>     <div class="vertical">
>         <div id="site-head-content" class="inner">
>
>             {{#if @blog.logo}}<a id="blog-logo" href="{{@blog.url}}"><img src="{{@blog.logo}}" alt="Blog Logo" /></a>{{/if}}
>             <h1 class="blog-title">{{@blog.title}}</h1>
>             <h2 class="blog-description">{{@blog.description}}</h2>
>             {{navigation}}
>         </div>
>     </div>
> </header>
>
12,14d26
<
<         {{! Everything inside the #post tags pulls data from the post }}
<         {{#post}}
```

**Comment by xdumaine** [comment]
I think I like this idea, but could you prepare a PR and I'll review?

**Comment by xdumaine** [comment]
I think this could be done without duplicating the header by using the `{{#is "post"}}` helper - so, something like:

```
<header id="site-head"
    {{#is "post"}}
        {{#if post.image}}
            style="background-image: url({{post.image}})"
        {{else}}
            {{#if @blog.cover}}
                style="background-image: url({{@blog.cover}})"
            {{/if}}
        {{/if}}
    {{else}}
        {{#if @blog.cover}}
            style="background-image: url({{@blog.cover}})"
        {{/if}}
    {{/is}}>
```

**Comment by xdumaine** [comment]
Resolved in [c54a9ccf](https://github.com/xdumaine/ghost-aside/commit/c54a9ccf0e77936d76c1b74a08accc7f07c7788e)

**Comment by xdumaine** [comment]
So I did add this, but I'm not sure I like it. Post images aren't necessarily big enough, quality enough, or in the right aspect ratio, etc, to look good as the sidebar/header image. I might revert this or maybe limit it to pages instead of posts, so pages use their image as the header image, but posts use the standard image. I think that makes it consistent with expectations, and gives the user the flexibility to use smaller images with posts, that show up as thumbnails in the list, or on the post itself, but doesn't force all of those to be huge, while still allowing pages to "hijack" the header with their own image.

**Comment by rhester72** [comment]
I actually love it (especially the thumbnail in the post list).  The reason I am not concerned about the AR:
- Casper is kind of the "gold standard" here, which muderously alters the image favoring the horizontal (while respecting AR, at least :)
- Expected cropping is very different between the desktop and mobile presentations, but again, this is mostly a non-issue since AR is preserved

In short, I hear where you're coming from as far as presentation, but given the image can be (and is) used in so many different presentation styles, both within and across themes, I don't think a "fix" is viable (or even desirable).  What you have now, at least to my eye, looks _good_, on both desktop and mobile.

More importantly, the theme is now consistent with Ghost guidelines on per-post image handling, which doesn't hurt, and is one of the reasons I became immediately attracted to your theme in the first place, since you have done a fantastic job of tracking Ghost development state.

The only wish-list thing I'd have re: image handling is some way of determining an appropriate overlay color - standard white works well in a lot of cases, but in some it can become very difficult to read well...ideally, there would be some way of determining the "average" pixel 'darkness' in the image and adjusting the text color for maximum contrast, but I fear my skills are not up to the task for something like that.  =)

(I forgot to add, yes, your method of keeping it clean and self-contained in default.hbs is the better solution - again, I was following the "Casper model", which in this case is not ideal.)

**Comment by xdumaine** [comment]
That's true. The pixel color detection would be pretty tough. This might be an option - just adding a text shadow to the header text. It's not a silver bullet, but it definitely helps. Compare without and with:

![screen shot 2015-04-10 at 11 38 03 am](https://cloud.githubusercontent.com/assets/833911/7091479/eb0e2e4a-df77-11e4-9a4c-d7bbfe352af8.png)
![screen shot 2015-04-10 at 11 38 15 am](https://cloud.githubusercontent.com/assets/833911/7091480/eb1021c8-df77-11e4-9f87-3eefe7ab43b8.png)

**Comment by rhester72** [comment]
VERY nice, and really "pops"!  Will look for the commit.  <G>
